### ISSUE TITLE
Simplifying the sed script for vasm conversion... 

### ISSUE THREAD

**Issue by realmml** [ggnkua/Arkos-Tracker-2-ST#1]
If you use in vasm the option "-spaces" (extra option in Motorola Syntax Module), you can use spaces in the expressions and you will not need to trim them.

**Comment by ggnkua** [comment]
Hi!

Thanks, I never knew about this option - I'll try it out and see how it goes!

**Comment by realmml** [comment]
You are welcome, i was the guy that suggested that option for vasm, hehehe.

You can find other specifics options for the Motorola Syntax Module in the manual section:
http://sun.hasenbraten.de/vasm/release/vasm_4.html#Mot-Syntax-Module

Maybe you can find another useful option there or if you need any extra option or directive, i would recommend you to write an email to Frank Wille, he is always very helpful.

**Comment by ggnkua** [comment]
> You can find other specifics options for the Motorola Syntax Module in the manual section:
>http://sun.hasenbraten.de/vasm/release/vasm_4.html#Mot-Syntax-Module
>
>Maybe you can find another useful option there

Actually I did! -align addresses the other issue I had, so thanks again! Changes verified and committed!
