### ISSUE TITLE
Possible 12-bit period of 4095 causes table overflow bug in timer prescaler logic.

### ISSUE THREAD

**Issue by em00k** [ggnkua/Arkos-Tracker-2-ST#5]
A good friend of mine may have found a bug on line https://github.com/ggnkua/Arkos-Tracker-2-ST/blob/fe21d5f446891c3b628b4324b360f88192dd2f44/sid.s#L316

```
timer_tab	dw	$0068,$0004,$0001 ;  104 :   4
	dw	$0105,$000a,$0002 ;  261 :  10
	dw	$01a2,$0010,$0003 ;  418 :  16
	dw	$051a,$0032,$0004 ; 1306 :  50
	dw	$0688,$0040,$0005 ; 1672 :  64
	dw	$0a35,$0064,$0006 ; 2613 : 100
	dw	$0eef,$00c8,$0007 ; 3823 : 200
	dw	$0fff,$00c8,$0007 ; 4095 : 200

; A 12-bit period of 4095 causes table overflow bug in timer prescaler logic.

; Previous entry shoud be; dw	$1000,$00c8,$0007 ; 4096 : 200
```

**Comment by ggnkua** [comment]
Hello,

Thanks for the report, I'll have a closer look and get back to you on this!

**Comment by ggnkua** [comment]
Forgot to ask: do you have a use case where the result is auditable on this? Would help a lot instead of doing things at blind.

**Comment by ggnkua** [comment]
Okay, I see what you meant. If d1=$fff (the biggest allowable value) then the MFP calculation would read garbo values. So this is fixed now, thanks again for the report!

**Comment by em00k** [comment]
Glad to have helped. We don't have any audio examples yet, but it was discovered while producing tables based on the calculations for a potential port to the ZX Next.
